server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=${API_PREFIX:/api/v1}/identity-service/**
              filters:
                - StripPrefix=2
            - id: profile-service
              uri: lb://profile-service
              predicates:
                - Path=${API_PREFIX:/api/v1}/profile-service/**
              filters:
                - StripPrefix=2
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=${API_PREFIX:/api/v1}/product-service/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: lb://product-service
              predicates:
                - Path=${API_PREFIX:/api/v1}/product-service/**
              filters:
                - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}